import { prisma } from '../db.js';

// --- 1. Generate Purchase Order (Buyer Only) ---
export const generatePurchaseOrder = async (req, res) => {
  const { quotationId } = req.body;

  if (!quotationId) return res.status(400).json({ error: 'quotationId is required' });

  try {
    // 1. Verify the quotation exists and is actually the winning bid
    const quotation = await prisma.quotation.findUnique({
      where: { id: quotationId },
      include: { rfq: true }
    });

    if (!quotation) return res.status(404).json({ error: 'Quotation not found' });
    if (quotation.status !== 'SELECTED') {
      return res.status(400).json({ error: 'Can only generate a PO from a SELECTED quotation' });
    }

    // 2. Check if a PO already exists to prevent duplicates
    const existingPo = await prisma.purchaseOrder.findUnique({
      where: { quotationId }
    });
    if (existingPo) {
      return res.status(409).json({ error: 'A Purchase Order already exists for this quotation' });
    }

    // 3. Auto-Calculate Totals (Hackathon logic: apply a flat 10% tax for realism)
    const subtotal = Number(quotation.totalAmount);
    const taxRate = 10.0; // 10%
    const taxAmount = (subtotal * taxRate) / 100;
    const totalAmount = subtotal + taxAmount;

    // 4. Generate a unique PO Number (e.g., PO-20260606-A1B2)
    const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, '');
    const randomHash = Math.random().toString(36).substring(2, 6).toUpperCase();
    const poNumber = `PO-${dateStr}-${randomHash}`;

    // 5. Create the PO
    const purchaseOrder = await prisma.purchaseOrder.create({
      data: {
        quotationId,
        vendorId: quotation.vendorId,
        createdById: req.user.id,
        orgId: req.user.orgId,
        poNumber,
        subtotal,
        taxRate,
        taxAmount,
        totalAmount,
        status: 'ISSUED' // Automatically set to Issued so the Vendor can see it
      }
    });

    res.status(201).json({ 
      message: 'Purchase Order generated successfully', 
      purchaseOrder 
    });

  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to generate Purchase Order' });
  }
};

// --- 2. Get All Purchase Orders (Dashboard) ---
export const getPurchaseOrders = async (req, res) => {
  try {
    let pos;

    if (req.user.role === 'VENDOR') {
      // Vendors see POs assigned to their company
      const vendorProfile = await prisma.vendor.findUnique({ where: { orgId: req.user.orgId } });
      if (!vendorProfile) return res.status(404).json({ error: 'Vendor profile not found' });

      pos = await prisma.purchaseOrder.findMany({
        where: { vendorId: vendorProfile.id },
        include: { org: { select: { name: true } } }, // See the Buyer's company name
        orderBy: { createdAt: 'desc' }
      });
    } else {
      // Buyers see POs generated by their company
      pos = await prisma.purchaseOrder.findMany({
        where: { orgId: req.user.orgId },
        include: { vendor: { include: { org: { select: { name: true } } } } }, // See Vendor name
        orderBy: { createdAt: 'desc' }
      });
    }

    res.json(pos);
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Failed to fetch Purchase Orders' });
  }
};